version: 2
jobs:
  build:
    filters:
      branches:
        ignore:
          - gh-pages
    docker:
      - image: circleci/node:8.11
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install depedencies
          command: yarn install
      - save_cache:
          paths:
            - web/node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Create folder if static images is not found
          command: mkdir -p /home/circleci/repo/static/img
      - run:
          name: Build Apps
          command: yarn prod
  linter:
    filters:
      branches:
        ignore:
          - gh-pages
    docker:
      - image: circleci/node:8.11
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install depedencies
          command: yarn install
      - save_cache:
          paths:
            - web/node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run Linter
          command: yarn lint
  test:
    filters:
      branches:
        ignore:
          - gh-pages
    docker:
      - image: circleci/node:8.11
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install depedencies
          command: yarn install
      - save_cache:
          paths:
            - web/node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run unit test
          command: yarn test
      - run:
          name: Set codecov
          command: node_modules/.bin/codecov --token=d566eab6-c25b-476c-8bd3-2d6bcaa7998c
  deploy:
    filters:
      branches:
        ignore:
          - gh-pages
    docker:
      - image: circleci/node:8.11
    working_directory: ~/repo
    environment:
      - SOURCE_BRANCH: master
      - TARGET_BRANCH: gh-pages
      - GH_EMAIL: irfanandriansyah10@gmail.com
      - GH_NAME: Irfan Andriansyah
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - add_ssh_keys:
          fingerprints:
            - "7f:a8:7c:7c:70:78:db:0e:ae:e5:9c:ac:e8:84:e5:c2"
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - deploy:
          name: Deploy
          command: |
            if [ $CIRCLE_BRANCH == $SOURCE_BRANCH ]; then
              git config --global user.email $GH_EMAIL
              git config --global user.name $GH_NAME

              git clone $CIRCLE_REPOSITORY_URL out

              cd out
              git checkout $TARGET_BRANCH || git checkout --orphan $TARGET_BRANCH
              git rm -rf .
              cd ..

              mkdir -p /home/circleci/repo/static/img
              yarn prod

              cp -a dist/. out/.

              mkdir -p out/.circleci && cp -a .circleci/. out/.circleci/.
              cd out

              git add -A
              git commit -m "Automated deployment to GitHub Pages: ${CIRCLE_SHA1}" --allow-empty

              git push origin $TARGET_BRANCH
            fi
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - develop
                - master
                - staging
      - linter:
          filters:
            branches:
              only:
                - develop
                - master
                - staging
          requires:
            - build
      - test:
          filters:
            branches:
              only:
                - develop
                - master
                - staging
          requires:
            - build
      - deploy:
          filters:
            branches:
              only:
                - develop
                - master
                - staging
          requires:
            - linter
            - test
